# Do not edit this file unless you know what you are doing
# 不要编辑本文件，除非你知道你在做什么

# 本文件是插件和主程序的桥梁
global_var = {}


def get_global(key):
    return global_var[key]


def set_global(key, value):
    global_var[key] = value


response_base = {
    "code": 0,
    "msg": "success",
    "data": None
}
